### ISSUE TITLE
powersave, ondemand?

### ISSUE THREAD

**Issue by cyrinux** [taradiddles/qubes-os#1]
Hi

What about add 

xenpm set-scaling-governor [0-3] powersave

Regards

**Comment by taradiddles** [comment]
Many apologies for seeing that issue after 1.5 years ; I must have missed the github notification and I haven't worked on power management for quite some time so I didn't see the pending issue.

Re- powersave governor: I remember reading that it was better for battery usage to "race" to complete a task and return to lower C states, rather than locking the frequency to the lowest one (which IIUC is what the 'powersave' governor does) and have the CPU spend more time completing a task.

**Comment by cyrinux** [comment]
Thanks for your reply @taradiddles ;)
